include: package:flutter_lints/flutter.yaml

linter:
  rules:
    avoid_print: true
    prefer_single_quotes: true
    require_trailing_comma: true
    always_use_package_imports: true
    prefer_final_locals: true
analyzer:
  errors:
    invalid_annotation_target: ignore
