// This file is "main.dart"
import 'package:freezed_annotation/freezed_annotation.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'notice_model.freezed.dart';
// optional: Since our Person class is serializable, we must add this line.
// But if Person was not serializable, we could skip it.
part 'notice_model.g.dart';

@freezed
class NoticeModel with _$NoticeModel {
  const factory NoticeModel({
    required int id,
    required String boardNum,
    required String name,
    required String boardDetail,
    required String writer,
    required String hits,
    required String url,
    required String? picUrl,
    required String? period,
    required String date,
  }) = _NoticeModel;

  factory NoticeModel.fromJson(Map<String, Object?> json) =>
      _$NoticeModelFromJson(json);
}
// "id": 395,
// "menu": "EVENT",
// "url": "https://cnuint.cnu.ac.kr/cnuint/notice/event.do?mode=view&articleNo=312718&article.offset=0&articleLimit=10",
// "name": "Sweden-Korea Nobel Memorial Program 2022 스웨덴-대한민국 노벨 메모리얼 프로그램",
// "hits": "69",
// "boardNum": "224",
// "date": "22.11.01",
// "writer": "국제교류본부",
// "picUrl": null,
// "period": null,
// "boardDetail": ""