// This file is "main.dart"
import 'package:freezed_annotation/freezed_annotation.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'shuttle_model.freezed.dart';
// optional: Since our Person class is serializable, we must add this line.
// But if Person was not serializable, we could skip it.
part 'shuttle_model.g.dart';

@freezed
class ShuttleModel with _$ShuttleModel {
  const factory ShuttleModel({
    required int id,
    required String name,
    required List<String>? emailPrefixList,
  }) = _ShuttleModel;

  factory ShuttleModel.fromJson(Map<String, Object?> json) =>
      _$ShuttleModelFromJson(json);
}
